### ISSUE TITLE
Tutorial: Run Standalone on Quest

### ISSUE THREAD

**Issue by CesiumBen** [CesiumGS/cesium-unreal-vr-tutorial#12]
### Build for Quest Release
Target release date: 8/19/2022 <br>

### Checklist

- [x] Complete technical implementation (updates in pr) #34   
- [x] Create a new version and upload to Unreal Engine Marketplace <- Pending PR #33
- [x] Complete text review, [Link](https://docs.google.com/document/d/12jAMMnm5CW66Un1hjBeWBq3SoeJjHVcjF7N3dIqnpTM/edit)
- [x] Publish page, [Prismic Page](https://cesium.prismic.io/documents~w=Quest&b=working&c=published&l=en-us/Yu2O7hAAACMAV70-/)  

#### References
[VR Tutorial on UE marketplace](https://www.unrealengine.com/marketplace/en-US/product/cesium-for-unreal-vr-tutorials/reviews)<br>
[VR series introduction on Cesium site](https://cesium.com/learn/unreal/vr-introduction/) <br>
[Google Drive folder](https://drive.google.com/drive/folders/1HjB710sAdvjJT4GxldsMP20LL6mZtres?usp=sharing) <br>

**Comment by LisaBosCesium** [comment]
@CesiumBen - @xuelongmu and I have completed our review in the doc.

**Comment by CesiumBen** [comment]
Thank you @LisaBosCesium and @xuelongmu! Release has been updated, please check staged releases in a bit after it updates.

**Comment by LisaBosCesium** [comment]
@CesiumBen 

Made a couple Prismic styling fixes, esp the one to remove the paragraph from the right nav that shouldn't be there. 

Ready to go now as far as I'm concerned.

**Comment by CesiumBen** [comment]
@LisaBosCesium Thank you! Will verify after staging updates and notify to release

**Comment by CesiumBen** [comment]
closing because have been released
