### ISSUE TITLE
Post VR Series to the Unreal Marketplace

### ISSUE THREAD

**Issue by LisaBosCesium** [CesiumGS/cesium-unreal-vr-tutorial#24]

**Comment by shehzan10** [comment]
I'm pretty sure this should be the same process as we have for Cesium for Unreal Samples. Please take a look at https://github.com/CesiumGS/cesium-unreal/blob/ue5-main/Documentation/release-process.md#update-cesium-for-unreal-samples for the release instructions for the Samples project and we can do essentially the same thing here.

**Comment by CesiumBen** [comment]
I've added images and updated the description to the release. I've tagged a release, and will edit should #26 get merged. 

@shehzan10 Should be good for review and awaiting final items.

**Comment by CesiumBen** [comment]
@shehzan10 I've posted #28 addressing the feedback we received
- Content is now nested entirely within a folder called "CesiumVRTutorial"
- Removed XRVisualization dependency

I think it's best that they test with an Oculus. I'm unsure as to why the Valve index would not work but would take longer for me to procure the headset and test than for someone else on their end to test with oculus. 

I am unsure what the reviewer means by listing "bridge" for ".uproject has unused plugins disabled". We don't have any dependency or plugin enabled for Quixel or megascans.
