### ISSUE TITLE
Tutorial: Viewing the globe

### ISSUE THREAD

**Issue by CesiumBen** [CesiumGS/cesium-unreal-vr-tutorial#5]
### Build for Quest Release
Target release date: 9/2/2022 <br>

### Checklist

- [x] Complete technical implementation [#37](https://github.com/CesiumGS/cesium-unreal-vr-tutorial/pull/37)   
- [x] Create a new version and upload to Unreal Engine Marketplace
- [x] Complete text review, [Link](https://docs.google.com/document/d/17yq7K7hlZUD7GdtQuLgjlt6pyASi3Q3ThybRyTGzlk8/edit#)
- [x] Publish page, [Release](https://cesium.prismic.io/documents/upcoming?r=Yxp5cBAAAIhmwj-i&l=en-us)  

#### References
[VR Tutorial on UE marketplace](https://www.unrealengine.com/marketplace/en-US/product/cesium-for-unreal-vr-tutorials/reviews)
[VR series introduction on Cesium site](https://cesium.com/learn/unreal/vr-introduction/)
[Google Drive folder](https://drive.google.com/drive/folders/1HjB710sAdvjJT4GxldsMP20LL6mZtres?usp=sharing)

**Comment by LisaBosCesium** [comment]
@CesiumBen I've completed a copy edit of the tutorial text. Over to @xuelongmu for a technical review.
