### ISSUE TITLE
Tutorial: Vignette for motion sickness

### ISSUE THREAD

**Issue by CesiumBen** [CesiumGS/cesium-unreal-vr-tutorial#6]

**Comment by LisaBosCesium** [comment]
PR merged - https://github.com/CesiumGS/cesium-unreal-vr-tutorial/pull/31

**Comment by shehzan10** [comment]
@CesiumBen Have we created a new release tag and published this on the Marketplace as well?

**Comment by CesiumBen** [comment]
@shehzan10 I've created a new release for 1.1 and updated the project file, version number, and link to release on the marketplace. I followed cesium for unreal samples pattern of updating the singular version file submitted in the marketplace instead of adding new version files on the plugin page.
