### ISSUE TITLE
Tutorial: Creating and interacting with dynamic world UI screens to show OSM metadata.

### ISSUE THREAD

**Issue by CesiumBen** [CesiumGS/cesium-unreal-vr-tutorial#8]
### Visualizing Metadata with Dynamic UI Release
Target release date: 10/13/2022 <br>

### Checklist

- [x] Complete technical implementation #40   
- [x] Create a new version and upload to Unreal Engine Marketplace
- [x] Complete text review, [Link](https://docs.google.com/document/d/1PhnhD7OO4dwxKlfS1-Q3GTppdA7PQbkc8ST1MqRp31k/edit#)
- [x] Publish page   

#### References
[VR Tutorial on UE marketplace](https://www.unrealengine.com/marketplace/en-US/product/cesium-for-unreal-vr-tutorials/reviews)
[VR series introduction on Cesium site](https://cesium.com/learn/unreal/vr-introduction/)
[Google Drive folder](https://drive.google.com/drive/folders/1HjB710sAdvjJT4GxldsMP20LL6mZtres?usp=sharing)

**Comment by xuelongmu** [comment]
Closing, as the tutorial has been published.
