### ISSUE TITLE
Tutorial: Saving and Loading Locations (lat/long/height)

### ISSUE THREAD

**Issue by CesiumBen** [CesiumGS/cesium-unreal-vr-tutorial#9]
### Saving and Loading Locations
Target release date: 1/13/2023 <br>

### Checklist

- [x] Complete technical implementation   
- [x] Create a new version and upload to Unreal Engine Marketplace
- [x] Complete text review, [Link](https://docs.google.com/document/d/10g6zY0Z40M8i-z3X5Nl4_cGUzdKvmTwYMJDNUaM_uCE/edit#)
- [x] Publish page   

#### References
[VR Tutorial on UE marketplace](https://www.unrealengine.com/marketplace/en-US/product/cesium-for-unreal-vr-tutorials/reviews)
[VR series introduction on Cesium site](https://cesium.com/learn/unreal/vr-introduction/)
[Google Drive folder](https://drive.google.com/drive/folders/1HjB710sAdvjJT4GxldsMP20LL6mZtres?usp=sharing)

**Comment by LisaBosCesium** [comment]
@CesiumBen @xuelongmu The text for the tutorial looks great. No outstanding comments to merge. I adjusted a few commas, that's about it. 

Time to create in Prismic? Don't wait for me to wrap it up!

**Comment by CesiumBen** [comment]
🎆 🎉
